enableGlobalCache: false

nodeLinker: pnp

yarnPath: .yarn/releases/yarn-4.5.0.cjs

packageExtensions:
  eslint-plugin-import@*:
    dependencies:
      eslint-import-resolver-node: '*'
  '@typescript-eslint/eslint-plugin@*':
    peerDependencies:
      typescript: '*'
