name: check_pull_request

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: ['main']
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn
      - run: yarn run lint
        working-directory: .
