name: Prepublish Storybook

on:
  pull_request:
    paths:
      - 'src/components/**'
    types: [opened, reopened, synchronize]
    branches: ['main']
  workflow_dispatch:

jobs:
  prepublish-storybook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: install packages
        run: yarn

      - name: deploy with chromatic
        id: chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: '👀 코드리뷰 전! Storybook 미리보기: ${{ steps.chromatic.outputs.storybookUrl }}'
